"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DJANGO_ENV = os.getenv("DJANGO_ENV", "development")
env_file = BASE_DIR / f".env.{DJANGO_ENV}"

if env_file.exists():
    load_dotenv(env_file)
else:
    load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"


def get_env_list(name, default=None):
    if default is None:
        default = []

    raw_value = os.getenv(name)
    if not raw_value:
        return default

    return [item.strip() for item in raw_value.split(",") if item.strip()]


def get_env_bool(name, default=False):
    raw_value = os.getenv(name)

    if raw_value is None:
        return default

    return raw_value.lower() in {"1", "true", "yes", "on"}


def build_postgres_database_config(host, port):
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": host,
        "PORT": port,
        "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
        "CONN_HEALTH_CHECKS": get_env_bool("DB_CONN_HEALTH_CHECKS", True),
    }


ALLOWED_HOSTS = get_env_list(
    "ALLOWED_HOSTS",
    ["127.0.0.1", "localhost"],
)
# CORS Settings the allowed origins for the frontend application 
# the frontend application is running on http://localhost:5173
CORS_ALLOWED_ORIGINS = get_env_list(
    "CORS_ALLOWED_ORIGINS",
    ["http://localhost:5173"],
)
CSRF_TRUSTED_ORIGINS = get_env_list("CSRF_TRUSTED_ORIGINS", [])
USE_X_FORWARDED_HOST = get_env_bool("USE_X_FORWARDED_HOST", False)
SECURE_SSL_REDIRECT = get_env_bool("SECURE_SSL_REDIRECT", False)
SESSION_COOKIE_SECURE = get_env_bool("SESSION_COOKIE_SECURE", False)
CSRF_COOKIE_SECURE = get_env_bool("CSRF_COOKIE_SECURE", False)

if get_env_bool("USE_SECURE_PROXY_SSL_HEADER", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',

    'users',
    'rooms',
    'bookings',
    'reviews',
    'smart_services',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.DatabaseRoutingMiddleware',
    'config.middleware.ApiRequestLogMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DB_ENGINE = os.getenv("DB_ENGINE", "sqlite")
DB_READ_REPLICA_ALIASES = ()
DATABASE_ROUTERS = []
DB_FORCE_PRIMARY_FOR_UNSAFE_METHODS = get_env_bool("DB_FORCE_PRIMARY_FOR_UNSAFE_METHODS", True)

# Using sqlite in the local environment
# Using postgresql in the production environment
if DB_ENGINE == "sqlite":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / os.getenv("SQLITE_NAME", "db.sqlite3"),
        }
    }
else:
    DATABASES = {
        "default": build_postgres_database_config(
            os.getenv("DB_HOST"),
            os.getenv("DB_PORT"),
        )
    }

    replica_hosts = get_env_list("DB_READ_REPLICA_HOSTS")
    replica_ports = get_env_list("DB_READ_REPLICA_PORTS")

    replica_aliases = []

    for index, replica_host in enumerate(replica_hosts, start=1):
        replica_alias = f"replica_{index}"
        replica_port = replica_ports[index - 1] if index - 1 < len(replica_ports) else os.getenv("DB_PORT")
        DATABASES[replica_alias] = build_postgres_database_config(replica_host, replica_port)
        replica_aliases.append(replica_alias)

    DB_READ_REPLICA_ALIASES = tuple(replica_aliases)

    if DB_READ_REPLICA_ALIASES:
        DATABASE_ROUTERS = ['config.database.router.PrimaryReplicaRouter']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# keep a concrete static files directory available for dockerized nginx deployments
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'



# REST Framework Settings 
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions

    # JWT Authentication is used for authentication
    # DRF will use the JWTAuthentication class to get the token from the request header
    # if the token is valid, DRF will set the request.user to the user associated with the token
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    # Allow read-only access for unauthenticated users
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}


REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:5013/1")
REDIS_CLUSTER_ENABLED = get_env_bool("REDIS_CLUSTER_ENABLED", False)
REDIS_CLUSTER_NODES = get_env_list("REDIS_CLUSTER_NODES")

if REDIS_CLUSTER_ENABLED and REDIS_CLUSTER_NODES:
    CACHES = {
        "default": {
            "BACKEND": "config.cache.redis_cluster.RedisClusterCache",
            "LOCATION": REDIS_CLUSTER_NODES,
            "TIMEOUT": 300,
            "KEY_PREFIX": "study_room_booking_system",
            "OPTIONS": {
                "read_from_replicas": get_env_bool("REDIS_CLUSTER_READ_FROM_REPLICAS", True),
                "require_full_coverage": get_env_bool("REDIS_CLUSTER_REQUIRE_FULL_COVERAGE", True),
                "address_remap": os.getenv("REDIS_CLUSTER_ADDRESS_REMAP", ""),
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "TIMEOUT": 300,
            "KEY_PREFIX": "study_room_booking_system",
        }
    }

JAVA_RECOMMENDATION_GRPC_TARGET = os.getenv("JAVA_RECOMMENDATION_GRPC_TARGET", "localhost:5101")
GO_AVAILABILITY_GRPC_TARGET = os.getenv("GO_AVAILABILITY_GRPC_TARGET", "localhost:5102")
JAVA_BOOKING_LIFECYCLE_GRPC_TARGET = os.getenv(
    "JAVA_BOOKING_LIFECYCLE_GRPC_TARGET",
    JAVA_RECOMMENDATION_GRPC_TARGET,
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "timestamped": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "timestamped",
        },
    },
    "loggers": {
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "api.access": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
