# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import study_room_services_pb2 as study__room__services__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in study_room_services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoomRecommendationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecommendRooms = channel.unary_unary(
                '/studyroom.v1.RoomRecommendationService/RecommendRooms',
                request_serializer=study__room__services__pb2.RecommendationRequest.SerializeToString,
                response_deserializer=study__room__services__pb2.RecommendationResponse.FromString,
                _registered_method=True)


class RoomRecommendationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecommendRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoomRecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecommendRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendRooms,
                    request_deserializer=study__room__services__pb2.RecommendationRequest.FromString,
                    response_serializer=study__room__services__pb2.RecommendationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'studyroom.v1.RoomRecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('studyroom.v1.RoomRecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoomRecommendationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecommendRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/studyroom.v1.RoomRecommendationService/RecommendRooms',
            study__room__services__pb2.RecommendationRequest.SerializeToString,
            study__room__services__pb2.RecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AvailabilityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindAvailableSlots = channel.unary_unary(
                '/studyroom.v1.AvailabilityService/FindAvailableSlots',
                request_serializer=study__room__services__pb2.AvailabilityRequest.SerializeToString,
                response_deserializer=study__room__services__pb2.AvailabilityResponse.FromString,
                _registered_method=True)


class AvailabilityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindAvailableSlots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AvailabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindAvailableSlots': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAvailableSlots,
                    request_deserializer=study__room__services__pb2.AvailabilityRequest.FromString,
                    response_serializer=study__room__services__pb2.AvailabilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'studyroom.v1.AvailabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('studyroom.v1.AvailabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AvailabilityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindAvailableSlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/studyroom.v1.AvailabilityService/FindAvailableSlots',
            study__room__services__pb2.AvailabilityRequest.SerializeToString,
            study__room__services__pb2.AvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BookingLifecycleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindExpiredPendingBookings = channel.unary_unary(
                '/studyroom.v1.BookingLifecycleService/FindExpiredPendingBookings',
                request_serializer=study__room__services__pb2.ExpiredPendingBookingsRequest.SerializeToString,
                response_deserializer=study__room__services__pb2.ExpiredPendingBookingsResponse.FromString,
                _registered_method=True)


class BookingLifecycleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindExpiredPendingBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingLifecycleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindExpiredPendingBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.FindExpiredPendingBookings,
                    request_deserializer=study__room__services__pb2.ExpiredPendingBookingsRequest.FromString,
                    response_serializer=study__room__services__pb2.ExpiredPendingBookingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'studyroom.v1.BookingLifecycleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('studyroom.v1.BookingLifecycleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookingLifecycleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindExpiredPendingBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/studyroom.v1.BookingLifecycleService/FindExpiredPendingBookings',
            study__room__services__pb2.ExpiredPendingBookingsRequest.SerializeToString,
            study__room__services__pb2.ExpiredPendingBookingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
