// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: study_room_services.proto

package studyroompb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomName       string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Capacity       int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	BuildingId     int64                  `protobuf:"varint,4,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`
	BuildingName   string                 `protobuf:"bytes,5,opt,name=building_name,json=buildingName,proto3" json:"building_name,omitempty"`
	EquipmentNames []string               `protobuf:"bytes,6,rep,name=equipment_names,json=equipmentNames,proto3" json:"equipment_names,omitempty"`
	IsActive       bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoomSnapshot) Reset() {
	*x = RoomSnapshot{}
	mi := &file_study_room_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSnapshot) ProtoMessage() {}

func (x *RoomSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_study_room_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSnapshot.ProtoReflect.Descriptor instead.
func (*RoomSnapshot) Descriptor() ([]byte, []int) {
	return file_study_room_services_proto_rawDescGZIP(), []int{0}
}

func (x *RoomSnapshot) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomSnapshot) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomSnapshot) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *RoomSnapshot) GetBuildingId() int64 {
	if x != nil {
		return x.BuildingId
	}
	return 0
}

func (x *RoomSnapshot) GetBuildingName() string {
	if x != nil {
		return x.BuildingName
	}
	return ""
}

func (x *RoomSnapshot) GetEquipmentNames() []string {
	if x != nil {
		return x.EquipmentNames
	}
	return nil
}

func (x *RoomSnapshot) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type BookingSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	BookingDate   string                 `protobuf:"bytes,2,opt,name=booking_date,json=bookingDate,proto3" json:"booking_date,omitempty"` // YYYY-MM-DD
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`       // HH:MM
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`             // HH:MM
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingSnapshot) Reset() {
	*x = BookingSnapshot{}
	mi := &file_study_room_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingSnapshot) ProtoMessage() {}

func (x *BookingSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_study_room_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingSnapshot.ProtoReflect.Descriptor instead.
func (*BookingSnapshot) Descriptor() ([]byte, []int) {
	return file_study_room_services_proto_rawDescGZIP(), []int{1}
}

func (x *BookingSnapshot) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *BookingSnapshot) GetBookingDate() string {
	if x != nil {
		return x.BookingDate
	}
	return ""
}

func (x *BookingSnapshot) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *BookingSnapshot) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *BookingSnapshot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReviewStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	AverageRating float64                `protobuf:"fixed64,2,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	ReviewCount   int32                  `protobuf:"varint,3,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewStat) Reset() {
	*x = ReviewStat{}
	mi := &file_study_room_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewStat) ProtoMessage() {}

func (x *ReviewStat) ProtoReflect() protoreflect.Message {
	mi := &file_study_room_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewStat.ProtoReflect.Descriptor instead.
func (*ReviewStat) Descriptor() ([]byte, []int) {
	return file_study_room_services_proto_rawDescGZIP(), []int{2}
}

func (x *ReviewStat) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ReviewStat) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *ReviewStat) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

type RecommendationRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BookingDate         string                 `protobuf:"bytes,1,opt,name=booking_date,json=bookingDate,proto3" json:"booking_date,omitempty"`
	StartTime           string                 `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime             string                 `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MinCapacity         int32                  `protobuf:"varint,4,opt,name=min_capacity,json=minCapacity,proto3" json:"min_capacity,omitempty"`
	RequiredEquipment   []string               `protobuf:"bytes,5,rep,name=required_equipment,json=requiredEquipment,proto3" json:"required_equipment,omitempty"`
	PreferredBuildingId int64                  `protobuf:"varint,6,opt,name=preferred_building_id,json=preferredBuildingId,proto3" json:"preferred_building_id,omitempty"`
	Rooms               []*RoomSnapshot        `protobuf:"bytes,7,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Bookings            []*BookingSnapshot     `protobuf:"bytes,8,rep,name=bookings,proto3" json:"bookings,omitempty"`
	ReviewStats         []*ReviewStat          `protobuf:"bytes,9,rep,name=review_stats,json=reviewStats,proto3" json:"review_stats,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RecommendationRequest) Reset() {
	*x = RecommendationRequest{}
	mi := &file_study_room_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationRequest) ProtoMessage() {}

func (x *RecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_study_room_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationRequest.ProtoReflect.Descriptor instead.
func (*RecommendationRequest) Descriptor() ([]byte, []int) {
	return file_study_room_services_proto_rawDescGZIP(), []int{3}
}

func (x *RecommendationRequest) GetBookingDate() string {
	if x != nil {
		return x.BookingDate
	}
	return ""
}

func (x *RecommendationRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *RecommendationRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *RecommendationRequest) GetMinCapacity() int32 {
	if x != nil {
		return x.MinCapacity
	}
	return 0
}

func (x *RecommendationRequest) GetRequiredEquipment() []string {
	if x != nil {
		return x.RequiredEquipment
	}
	return nil
}

func (x *RecommendationRequest) GetPreferredBuildingId() int64 {
	if x != nil {
		return x.PreferredBuildingId
	}
	return 0
}

func (x *RecommendationRequest) GetRooms() []*RoomSnapshot {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *RecommendationRequest) GetBookings() []*BookingSnapshot {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *RecommendationRequest) GetReviewStats() []*ReviewStat {
	if x != nil {
		return x.ReviewStats
	}
	return nil
}

type RecommendedRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	BuildingName  string                 `protobuf:"bytes,3,opt,name=building_name,json=buildingName,proto3" json:"building_name,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendedRoom) Reset() {
	*x = RecommendedRoom{}
	mi := &file_study_room_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendedRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedRoom) ProtoMessage() {}

func (x *RecommendedRoom) ProtoReflect() protoreflect.Message {
	mi := &file_study_room_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedRoom.ProtoReflect.Descriptor instead.
func (*RecommendedRoom) Descriptor() ([]byte, []int) {
	return file_study_room_services_proto_rawDescGZIP(), []int{4}
}

func (x *RecommendedRoom) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RecommendedRoom) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RecommendedRoom) GetBuildingName() string {
	if x != nil {
		return x.BuildingName
	}
	return ""
}

func (x *RecommendedRoom) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RecommendedRoom) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RecommendationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RecommendedRoom     `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationResponse) Reset() {
	*x = RecommendationResponse{}
	mi := &file_study_room_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationResponse) ProtoMessage() {}

func (x *RecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_study_room_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationResponse.ProtoReflect.Descriptor instead.
func (*RecommendationResponse) Descriptor() ([]byte, []int) {
	return file_study_room_services_proto_rawDescGZIP(), []int{5}
}

func (x *RecommendationResponse) GetRooms() []*RecommendedRoom {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type AvailabilityRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BookingDate       string                 `protobuf:"bytes,1,opt,name=booking_date,json=bookingDate,proto3" json:"booking_date,omitempty"`
	SearchStartTime   string                 `protobuf:"bytes,2,opt,name=search_start_time,json=searchStartTime,proto3" json:"search_start_time,omitempty"`
	SearchEndTime     string                 `protobuf:"bytes,3,opt,name=search_end_time,json=searchEndTime,proto3" json:"search_end_time,omitempty"`
	DurationMinutes   int32                  `protobuf:"varint,4,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	MinCapacity       int32                  `protobuf:"varint,5,opt,name=min_capacity,json=minCapacity,proto3" json:"min_capacity,omitempty"`
	BuildingId        int64                  `protobuf:"varint,6,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`
	RequiredEquipment []string               `protobuf:"bytes,7,rep,name=required_equipment,json=requiredEquipment,proto3" json:"required_equipment,omitempty"`
	Rooms             []*RoomSnapshot        `protobuf:"bytes,8,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Bookings          []*BookingSnapshot     `protobuf:"bytes,9,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AvailabilityRequest) Reset() {
	*x = AvailabilityRequest{}
	mi := &file_study_room_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityRequest) ProtoMessage() {}

func (x *AvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_study_room_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityRequest.ProtoReflect.Descriptor instead.
func (*AvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_study_room_services_proto_rawDescGZIP(), []int{6}
}

func (x *AvailabilityRequest) GetBookingDate() string {
	if x != nil {
		return x.BookingDate
	}
	return ""
}

func (x *AvailabilityRequest) GetSearchStartTime() string {
	if x != nil {
		return x.SearchStartTime
	}
	return ""
}

func (x *AvailabilityRequest) GetSearchEndTime() string {
	if x != nil {
		return x.SearchEndTime
	}
	return ""
}

func (x *AvailabilityRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *AvailabilityRequest) GetMinCapacity() int32 {
	if x != nil {
		return x.MinCapacity
	}
	return 0
}

func (x *AvailabilityRequest) GetBuildingId() int64 {
	if x != nil {
		return x.BuildingId
	}
	return 0
}

func (x *AvailabilityRequest) GetRequiredEquipment() []string {
	if x != nil {
		return x.RequiredEquipment
	}
	return nil
}

func (x *AvailabilityRequest) GetRooms() []*RoomSnapshot {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *AvailabilityRequest) GetBookings() []*BookingSnapshot {
	if x != nil {
		return x.Bookings
	}
	return nil
}

type AvailableSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	BuildingName  string                 `protobuf:"bytes,3,opt,name=building_name,json=buildingName,proto3" json:"building_name,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableSlot) Reset() {
	*x = AvailableSlot{}
	mi := &file_study_room_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableSlot) ProtoMessage() {}

func (x *AvailableSlot) ProtoReflect() protoreflect.Message {
	mi := &file_study_room_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableSlot.ProtoReflect.Descriptor instead.
func (*AvailableSlot) Descriptor() ([]byte, []int) {
	return file_study_room_services_proto_rawDescGZIP(), []int{7}
}

func (x *AvailableSlot) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *AvailableSlot) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *AvailableSlot) GetBuildingName() string {
	if x != nil {
		return x.BuildingName
	}
	return ""
}

func (x *AvailableSlot) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *AvailableSlot) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type AvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*AvailableSlot       `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailabilityResponse) Reset() {
	*x = AvailabilityResponse{}
	mi := &file_study_room_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityResponse) ProtoMessage() {}

func (x *AvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_study_room_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityResponse.ProtoReflect.Descriptor instead.
func (*AvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_study_room_services_proto_rawDescGZIP(), []int{8}
}

func (x *AvailabilityResponse) GetSlots() []*AvailableSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

var File_study_room_services_proto protoreflect.FileDescriptor

const file_study_room_services_proto_rawDesc = "" +
	"\n" +
	"\x19study_room_services.proto\x12\fstudyroom.v1\"\xec\x01\n" +
	"\fRoomSnapshot\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12\x1f\n" +
	"\vbuilding_id\x18\x04 \x01(\x03R\n" +
	"buildingId\x12#\n" +
	"\rbuilding_name\x18\x05 \x01(\tR\fbuildingName\x12'\n" +
	"\x0fequipment_names\x18\x06 \x03(\tR\x0eequipmentNames\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"\x9f\x01\n" +
	"\x0fBookingSnapshot\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12!\n" +
	"\fbooking_date\x18\x02 \x01(\tR\vbookingDate\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"o\n" +
	"\n" +
	"ReviewStat\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12%\n" +
	"\x0eaverage_rating\x18\x02 \x01(\x01R\raverageRating\x12!\n" +
	"\freview_count\x18\x03 \x01(\x05R\vreviewCount\"\xa4\x03\n" +
	"\x15RecommendationRequest\x12!\n" +
	"\fbooking_date\x18\x01 \x01(\tR\vbookingDate\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\tR\aendTime\x12!\n" +
	"\fmin_capacity\x18\x04 \x01(\x05R\vminCapacity\x12-\n" +
	"\x12required_equipment\x18\x05 \x03(\tR\x11requiredEquipment\x122\n" +
	"\x15preferred_building_id\x18\x06 \x01(\x03R\x13preferredBuildingId\x120\n" +
	"\x05rooms\x18\a \x03(\v2\x1a.studyroom.v1.RoomSnapshotR\x05rooms\x129\n" +
	"\bbookings\x18\b \x03(\v2\x1d.studyroom.v1.BookingSnapshotR\bbookings\x12;\n" +
	"\freview_stats\x18\t \x03(\v2\x18.studyroom.v1.ReviewStatR\vreviewStats\"\x9a\x01\n" +
	"\x0fRecommendedRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12#\n" +
	"\rbuilding_name\x18\x03 \x01(\tR\fbuildingName\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"M\n" +
	"\x16RecommendationResponse\x123\n" +
	"\x05rooms\x18\x01 \x03(\v2\x1d.studyroom.v1.RecommendedRoomR\x05rooms\"\x97\x03\n" +
	"\x13AvailabilityRequest\x12!\n" +
	"\fbooking_date\x18\x01 \x01(\tR\vbookingDate\x12*\n" +
	"\x11search_start_time\x18\x02 \x01(\tR\x0fsearchStartTime\x12&\n" +
	"\x0fsearch_end_time\x18\x03 \x01(\tR\rsearchEndTime\x12)\n" +
	"\x10duration_minutes\x18\x04 \x01(\x05R\x0fdurationMinutes\x12!\n" +
	"\fmin_capacity\x18\x05 \x01(\x05R\vminCapacity\x12\x1f\n" +
	"\vbuilding_id\x18\x06 \x01(\x03R\n" +
	"buildingId\x12-\n" +
	"\x12required_equipment\x18\a \x03(\tR\x11requiredEquipment\x120\n" +
	"\x05rooms\x18\b \x03(\v2\x1a.studyroom.v1.RoomSnapshotR\x05rooms\x129\n" +
	"\bbookings\x18\t \x03(\v2\x1d.studyroom.v1.BookingSnapshotR\bbookings\"\xa4\x01\n" +
	"\rAvailableSlot\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12#\n" +
	"\rbuilding_name\x18\x03 \x01(\tR\fbuildingName\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\"I\n" +
	"\x14AvailabilityResponse\x121\n" +
	"\x05slots\x18\x01 \x03(\v2\x1b.studyroom.v1.AvailableSlotR\x05slots2x\n" +
	"\x19RoomRecommendationService\x12[\n" +
	"\x0eRecommendRooms\x12#.studyroom.v1.RecommendationRequest\x1a$.studyroom.v1.RecommendationResponse2r\n" +
	"\x13AvailabilityService\x12[\n" +
	"\x12FindAvailableSlots\x12!.studyroom.v1.AvailabilityRequest\x1a\".studyroom.v1.AvailabilityResponseBQ\n" +
	"\x12com.studynest.grpcB\x16StudyRoomServicesProtoP\x01Z!study-room-grpc/proto;studyroompbb\x06proto3"

var (
	file_study_room_services_proto_rawDescOnce sync.Once
	file_study_room_services_proto_rawDescData []byte
)

func file_study_room_services_proto_rawDescGZIP() []byte {
	file_study_room_services_proto_rawDescOnce.Do(func() {
		file_study_room_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_study_room_services_proto_rawDesc), len(file_study_room_services_proto_rawDesc)))
	})
	return file_study_room_services_proto_rawDescData
}

var file_study_room_services_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_study_room_services_proto_goTypes = []any{
	(*RoomSnapshot)(nil),           // 0: studyroom.v1.RoomSnapshot
	(*BookingSnapshot)(nil),        // 1: studyroom.v1.BookingSnapshot
	(*ReviewStat)(nil),             // 2: studyroom.v1.ReviewStat
	(*RecommendationRequest)(nil),  // 3: studyroom.v1.RecommendationRequest
	(*RecommendedRoom)(nil),        // 4: studyroom.v1.RecommendedRoom
	(*RecommendationResponse)(nil), // 5: studyroom.v1.RecommendationResponse
	(*AvailabilityRequest)(nil),    // 6: studyroom.v1.AvailabilityRequest
	(*AvailableSlot)(nil),          // 7: studyroom.v1.AvailableSlot
	(*AvailabilityResponse)(nil),   // 8: studyroom.v1.AvailabilityResponse
}
var file_study_room_services_proto_depIdxs = []int32{
	0, // 0: studyroom.v1.RecommendationRequest.rooms:type_name -> studyroom.v1.RoomSnapshot
	1, // 1: studyroom.v1.RecommendationRequest.bookings:type_name -> studyroom.v1.BookingSnapshot
	2, // 2: studyroom.v1.RecommendationRequest.review_stats:type_name -> studyroom.v1.ReviewStat
	4, // 3: studyroom.v1.RecommendationResponse.rooms:type_name -> studyroom.v1.RecommendedRoom
	0, // 4: studyroom.v1.AvailabilityRequest.rooms:type_name -> studyroom.v1.RoomSnapshot
	1, // 5: studyroom.v1.AvailabilityRequest.bookings:type_name -> studyroom.v1.BookingSnapshot
	7, // 6: studyroom.v1.AvailabilityResponse.slots:type_name -> studyroom.v1.AvailableSlot
	3, // 7: studyroom.v1.RoomRecommendationService.RecommendRooms:input_type -> studyroom.v1.RecommendationRequest
	6, // 8: studyroom.v1.AvailabilityService.FindAvailableSlots:input_type -> studyroom.v1.AvailabilityRequest
	5, // 9: studyroom.v1.RoomRecommendationService.RecommendRooms:output_type -> studyroom.v1.RecommendationResponse
	8, // 10: studyroom.v1.AvailabilityService.FindAvailableSlots:output_type -> studyroom.v1.AvailabilityResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_study_room_services_proto_init() }
func file_study_room_services_proto_init() {
	if File_study_room_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_study_room_services_proto_rawDesc), len(file_study_room_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_study_room_services_proto_goTypes,
		DependencyIndexes: file_study_room_services_proto_depIdxs,
		MessageInfos:      file_study_room_services_proto_msgTypes,
	}.Build()
	File_study_room_services_proto = out.File
	file_study_room_services_proto_goTypes = nil
	file_study_room_services_proto_depIdxs = nil
}
