// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: study_room_services.proto

package studyroompb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomRecommendationService_RecommendRooms_FullMethodName = "/studyroom.v1.RoomRecommendationService/RecommendRooms"
)

// RoomRecommendationServiceClient is the client API for RoomRecommendationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoomRecommendationServiceClient interface {
	RecommendRooms(ctx context.Context, in *RecommendationRequest, opts ...grpc.CallOption) (*RecommendationResponse, error)
}

type roomRecommendationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomRecommendationServiceClient(cc grpc.ClientConnInterface) RoomRecommendationServiceClient {
	return &roomRecommendationServiceClient{cc}
}

func (c *roomRecommendationServiceClient) RecommendRooms(ctx context.Context, in *RecommendationRequest, opts ...grpc.CallOption) (*RecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendationResponse)
	err := c.cc.Invoke(ctx, RoomRecommendationService_RecommendRooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomRecommendationServiceServer is the server API for RoomRecommendationService service.
// All implementations must embed UnimplementedRoomRecommendationServiceServer
// for forward compatibility.
type RoomRecommendationServiceServer interface {
	RecommendRooms(context.Context, *RecommendationRequest) (*RecommendationResponse, error)
	mustEmbedUnimplementedRoomRecommendationServiceServer()
}

// UnimplementedRoomRecommendationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomRecommendationServiceServer struct{}

func (UnimplementedRoomRecommendationServiceServer) RecommendRooms(context.Context, *RecommendationRequest) (*RecommendationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecommendRooms not implemented")
}
func (UnimplementedRoomRecommendationServiceServer) mustEmbedUnimplementedRoomRecommendationServiceServer() {
}
func (UnimplementedRoomRecommendationServiceServer) testEmbeddedByValue() {}

// UnsafeRoomRecommendationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomRecommendationServiceServer will
// result in compilation errors.
type UnsafeRoomRecommendationServiceServer interface {
	mustEmbedUnimplementedRoomRecommendationServiceServer()
}

func RegisterRoomRecommendationServiceServer(s grpc.ServiceRegistrar, srv RoomRecommendationServiceServer) {
	// If the following call panics, it indicates UnimplementedRoomRecommendationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomRecommendationService_ServiceDesc, srv)
}

func _RoomRecommendationService_RecommendRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomRecommendationServiceServer).RecommendRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomRecommendationService_RecommendRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomRecommendationServiceServer).RecommendRooms(ctx, req.(*RecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomRecommendationService_ServiceDesc is the grpc.ServiceDesc for RoomRecommendationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomRecommendationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "studyroom.v1.RoomRecommendationService",
	HandlerType: (*RoomRecommendationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecommendRooms",
			Handler:    _RoomRecommendationService_RecommendRooms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "study_room_services.proto",
}

const (
	AvailabilityService_FindAvailableSlots_FullMethodName = "/studyroom.v1.AvailabilityService/FindAvailableSlots"
)

// AvailabilityServiceClient is the client API for AvailabilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AvailabilityServiceClient interface {
	FindAvailableSlots(ctx context.Context, in *AvailabilityRequest, opts ...grpc.CallOption) (*AvailabilityResponse, error)
}

type availabilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAvailabilityServiceClient(cc grpc.ClientConnInterface) AvailabilityServiceClient {
	return &availabilityServiceClient{cc}
}

func (c *availabilityServiceClient) FindAvailableSlots(ctx context.Context, in *AvailabilityRequest, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, AvailabilityService_FindAvailableSlots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AvailabilityServiceServer is the server API for AvailabilityService service.
// All implementations must embed UnimplementedAvailabilityServiceServer
// for forward compatibility.
type AvailabilityServiceServer interface {
	FindAvailableSlots(context.Context, *AvailabilityRequest) (*AvailabilityResponse, error)
	mustEmbedUnimplementedAvailabilityServiceServer()
}

// UnimplementedAvailabilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAvailabilityServiceServer struct{}

func (UnimplementedAvailabilityServiceServer) FindAvailableSlots(context.Context, *AvailabilityRequest) (*AvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAvailableSlots not implemented")
}
func (UnimplementedAvailabilityServiceServer) mustEmbedUnimplementedAvailabilityServiceServer() {}
func (UnimplementedAvailabilityServiceServer) testEmbeddedByValue()                             {}

// UnsafeAvailabilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvailabilityServiceServer will
// result in compilation errors.
type UnsafeAvailabilityServiceServer interface {
	mustEmbedUnimplementedAvailabilityServiceServer()
}

func RegisterAvailabilityServiceServer(s grpc.ServiceRegistrar, srv AvailabilityServiceServer) {
	// If the following call panics, it indicates UnimplementedAvailabilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AvailabilityService_ServiceDesc, srv)
}

func _AvailabilityService_FindAvailableSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvailabilityServiceServer).FindAvailableSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvailabilityService_FindAvailableSlots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvailabilityServiceServer).FindAvailableSlots(ctx, req.(*AvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AvailabilityService_ServiceDesc is the grpc.ServiceDesc for AvailabilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AvailabilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "studyroom.v1.AvailabilityService",
	HandlerType: (*AvailabilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAvailableSlots",
			Handler:    _AvailabilityService_FindAvailableSlots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "study_room_services.proto",
}
